{% set name = "multi_rake" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 14bcf5febde321b62829ec0ba3f4a49615112d88c952d86f0ab53c0d5fdd7440

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.14.4
    - pycld2 >=0.41
    - python
    - pyrsistent >=0.14.2
    - regex >=2018.6.6

test:
  imports:
    - multi_rake

about:
  home: "https://github.com/vgrabovets/multi_rake"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Multilingual Rapid Keyword Extraction (RAKE)"
  dev_url: "https://github.com/vgrabovets/multi_rake"

extra:
  recipe-maintainers:
    - mxr-conda
    - d-cunningham
    - JennaLipscomb
